# Generated by Django 4.1.1 on 2022-10-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_product_category_alter_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='comapny_address',
            new_name='company_address',
        ),
    ]
