# Generated by Django 4.1.1 on 2022-12-15 07:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=accounts.models.upload_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_banner',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_path),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_path),
        ),
        migrations.AlterField(
            model_name='seller',
            name='company_pan_document',
            field=models.ImageField(blank=True, upload_to=accounts.models.upload_path),
        ),
    ]
