# Generated by Django 4.1.1 on 2022-10-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seller_company_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='password2',
        ),
    ]
